### PR TITLE
updated fv3config requirement to 0.8.0

### PR DESCRIPTION
**Pull request by brianhenn**

### CODE REVIEW

**Review by ofuhrer — APPROVED** [review]
LGTM

**Comment by nbren12** [comment]
LGTM. I would update gcsfs to latest as well for improved reliability.

**Comment by ofuhrer** [comment]
> LGTM. I would update gcsfs to latest as well for improved reliability.

@nbren12 Couldn't get anything `gcfs>=0.7.*` to pass our tests, so stuck with the highest passing version.

**Comment by nbren12** [comment]
@ofuhrer  You would need to update fsspec as well. fsspec 0.8.0 is not compatible with the newer versions. Newer versions of pip would have shown a version conflict error.

It sounds like this repo is not properly pinning its python dependencies and ensuring these are no version conflicts.

**Comment by nbren12** [comment]
We ran into numerous problems of this nature on fv3net given the instability of the fsspec stack and its dependencies. fv3gfs-fortran also doesn't appear transitive dependencies (deps of deps) so could break from one of those changes.

**Comment by ofuhrer** [comment]
@nbren12 Correct. We have a strategy to fix this afaik, and @mcgibbon as well as @jdahm have done that on other repos afaik. Add an issue for this repo?

**Comment by nbren12** [comment]
Good to know plans are afoot. We've had a lot of success with pip-compile in fv3net to deal with this.

**Pull request merged**
