### PR TITLE
Compile FMS with -DGFS_PHYS

### PR DESCRIPTION
**Pull request by oliverwm1**
Since we are compiling everything in `FV3/` with the `-DGFS_PHYS` flag, we should do the same for `FMS`. This will slightly change the physical constants the model uses (and make the constants consistent with assumptions made by coarsening procedures in [fv3net](https://github.com/VulcanClimateModeling/fv3net)).

### CODE REVIEW

**Comment by oliverwm1** [comment]
Partially addresses #28.

**Comment by rheacangeo** [comment]
Thank you! I had noticed this when porting the FMS constants and thought it was strange. Making them consistent sounds good. I am surprised the checks passed though -- shouldn't you need to update the md5sums of the regression data?

**Comment by oliverwm1** [comment]
> I think the md5sums should probably be updated as well? But otherwise, I approve!

Yeah I was also surprised (and concerned) that this passed the regression test. Looking at the CircleCI logs, it looks like a pre-built FMS image was pulled, which would explain why the test passed. I'll try running the test with docker layer caching off.

**Comment by oliverwm1** [comment]
>  I'll try running the test with docker layer caching off.

That didn't help, since the CircleCI config.yml still just calls `make pull_deps` and pulls the latest pre-built FMS, ESMF and SERIALBOX images and goes from there. If I understand correctly, the only way to have CircleCI test the model with a newer FMS version is to manually push the FMS image, but this seems a little risky, since then any other builds of `fv3gfs-fortran` or `fv3gfs-python` will use this latest version of FMS.

**Comment by oliverwm1** [comment]
I confirmed that the regression tests were failing locally when using the new FMS image built with -DGFS_PHYS. I updated the md5sum files and now expect the tests to fail on CircleCI because CircleCI is using the old FMS image.

**Comment by nbren12** [comment]
[Finalize code and configurations for production end-to-end runs](https://trello.com/c/GEWtGtf8/335-finalize-code-and-configurations-for-production-end-to-end-runs)

**Comment by oliverwm1** [comment]
I manually pushed an updated FMS image and now rerunning CircleCI tests.

**Pull request merged**
