### PR TITLE
Fix: Remove dependency on vcm virtual environment

### PR DESCRIPTION
**Pull request by ofuhrer**
Removes dependency on vcm_1.0 virtual environment stored in /project/s1053 and simply installs venv on the fly using `requirements.txt` file.

### CODE REVIEW

**Review by FlorianDeconinck — APPROVED** [review]
lgtm

**Review by mcgibbon — COMMENTED** [review]
There's no version pinning going on in this PR. Is that OK? It's possible we'll see failures that are just due to dependencies changing versions and breaking things, and spend a lot of time debugging under the assumption that our code change broke the branch.

**Comment by ofuhrer** [comment]
> There's no version pinning going on in this PR. Is that OK? It's possible we'll see failures that are just due to dependencies changing versions and breaking things, and spend a lot of time debugging under the assumption that our code change broke the branch.

**Comment by mcgibbon** [comment]
As we discussed on zoom, if you can add an appropriate `constraints.txt` file under `.jenkins/` and add it to each pip install command using `-c constraints.txt`, that would be sufficient for this PR.

**Comment by ofuhrer** [comment]
> As we discussed on zoom, if you can commit an appropriate `constraints.txt` file under `.jenkins/` and add it to each pip install command using `-c constraints.txt`, that would be sufficient for this PR.

I decided that for the time being I will simply use the existing `requirements.txt` file and opt for the same strategy as all other testing infrastructure in this repo. The change to using `constraints.txt` is an orthogonal change not related to this fix.

**Review by mcgibbon — APPROVED** [review]
While this does lose functionality (the venv approach pinned dependencies unless we manually updated them), I'm OK with making it consistent with what is used by CIrcleCI.

Be aware dependencies may break the build on daint without breaking on CircleCI, because of the caching system used by CircleCI.

We should prioritize a follow-on PR to pin dependencies using constraints.

**Pull request merged**
