### PR TITLE
Raise error for misconfigured 3D physics diagnostics

### PR DESCRIPTION
**Pull request by spencerkclark**
This is now the output upon model termination if this occurs.  As in #132, the previous termination would be an uninformative segmentation fault.

```
FATAL from PE     0: FV3GFS_io::fv3gfs_diag_register Outputting 3D diagnostics from the physics requires gfs_physics_nml.ldiag3d be set to true.


FATAL from PE     1: FV3GFS_io::fv3gfs_diag_register Outputting 3D diagnostics from the physics requires gfs_physics_nml.ldiag3d be set to true.


FATAL from PE     0: FV3GFS_io::fv3gfs_diag_register Outputting 3D diagnostics from the physics requires gfs_physics_nml.ldiag3d be set to true.

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 13 RUNNING AT 8fdbee4d008c
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

### CODE REVIEW

**Comment by nbren12** [comment]
Related to #130

**Review by nbren12 — APPROVED** [review]
LGTM. Thanks. Could you shorten the title? I'd also be okay with just setting `ldiag3d=.true.` and not killing the model.

**Comment by spencerkclark** [comment]
> Could you shorten the title?

Thanks, sure, that will produce a cleaner commit message.

>  I'd also be okay with just setting `ldiag3d=.true.` and not killing the model.

It's not this simple unfortunately, because currently memory is allocated for the 3D diagnostics buckets before the diagnostics themselves are registered.  So if we changed `ldiag3d` to `.true.` after we registered the diagnostics (read: parsed the diag_table), it would be too late.  We could probably refactor things so that it didn't have to be this way, but I'm not sure if it's worth it.

**Review by oelbert — APPROVED** [review]
LGTM

**Pull request merged**
