### PR TITLE
Bug fix in coarse_graining.F90

### PR DESCRIPTION
**Pull request by ofuhrer**
Fixes a bug in `atmos_model.F90` when diagnostics are called (`FV3GFS_diag_output()` on L918) but coarse-graining is not initialized and thus the dimensions (`is, ie, js, je`) of the argument `Atm(mytile)%delp(is:ie, js:je, :)` being passed in are not initialized.

The fix is to replace the call to get the dimensions to the `coarse_graining.F90` module with a call to `atmosphere_control_data` from `atmosphere.F90` which essentially does the same thing.

### CODE REVIEW

**Review by spencerkclark — COMMENTED** [review]
Thanks @ofuhrer -- another option I thought about would be to replace the call to `get_fine_array_bounds` in `atmos_model.F90` with a call to `atmosphere_control_data`.  Without the optional arguments, it is almost a drop-in replacement:

https://github.com/VulcanClimateModeling/fv3gfs-fortran/blob/b0cf94e21c7987a31fefd421ba741771b6dafbdb/FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90#L890-L904

Would you be opposed to using that approach?  I somewhat lean towards it because it does not rely on initializing the array bounds to non-sensical values in `coarse_graining.F90`.

**Comment by ofuhrer** [comment]
@spencerkclark I like the proposal. Just a question: It seems that you are passing in a slice of delp, which is only used in case coarse-graining is activated. So there must be logic inside the diagnostics related to coarse graining. Would it not make sense to move the slicing _inside_ the diagnostics and simply pass the full delp argument (without the slicing). Note also that passing a slice array typically generates a copy of the array, so it is not very efficient.

**Review by spencerkclark — APPROVED** [review]
Thanks — yes it should be possible to do as you suggest.  I will look into it tomorrow.

**Review by oelbert — APPROVED** [review]
LGTM

**Pull request merged**
